### ISSUE TITLE
incompatible with Stardew 1.6

### ISSUE THREAD

**Issue by benny-dreamly** [barteke22/StardewMods#3]
I love this mod so much! (Specifically Fishing Info Overlays) and was wondering if you could update it for 1.6! If not that's okay. I know you haven't made a commit to the repo in over 3 years, but I find the mod so helpful!

**Comment by ER-95** [comment]
@barteke22 Are you updating your mods for 1.6? Thank you!

**Comment by benny-dreamly** [comment]
I think I can try converting this as it’s under an MIT license which means it’s fully open source. I have to learn c# first though………

**Comment by laz-xyr** [comment]
I fixed it. A lot of methods don't work. There may be some minor problems

**Comment by crazy531** [comment]
I fixed it. A lot of methods don't work. There may be some minor problems

**Comment by ER-95** [comment]
@crazy531 Would you be able to upload it here please? Thank you!

**Comment by laz-xyr** [comment]
[FishingInfoOverlays 1.1.6-unofficial.8.zip](https://github.com/barteke22/StardewMods/files/15033988/FishingInfoOverlays.1.1.6-unofficial.8.zip)

**Comment by ER-95** [comment]
@crazy531 Thank you! When you say "a lot of methods don't work", do you mean a lot of things were broken and had to be fixed? Or a lot of the mod still doesn't work?

**Comment by benny-dreamly** [comment]
@crazy531 thank you so much! I was trying to patch it myself but couldn't do it 👍

**Comment by benny-dreamly** [comment]
@crazy531 one small problem the lines you're using int.Parse could be replaced by an int.TryParse to avoid this mess of the log getting spammed with lots of red error messages like this: ```[18:27:29 ERROR Fishing Info Overlays] This mod failed in the Display.Rendered event. Technical details: 
FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at StardewMods.Overlay.Rendered(Object sender, RenderedEventArgs e) in C:\Users\xyr\OneDrive\game\Stardew Valley\FishingInfoOverlays\Overlay.cs:line 218
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101```

**Comment by laz-xyr** [comment]
> @crazy531 Thank you! When you say "a lot of methods don't work", do you mean a lot of things were broken and had to be fixed? Or a lot of the mod still doesn't work?
@ER-95 The fishing minigame box couldn't override the original BobberBar, couldn't find the right scale, Vector2 calculations were too difficult for me, I removed this feature myself and replaced it with another mod. I like is the top-left prediction function

**Comment by laz-xyr** [comment]
@benny-dreamly  The main change is the structure of the item, the type int of itemid has been changed to string, and the unique value is prefixed with (O). There are many places in the code that require int.TryParse conversions

**Comment by laz-xyr** [comment]
> @crazy531 one small problem the lines you're using int.Parse could be replaced by an int.TryParse to avoid this mess of the log getting spammed with lots of red error messages like this: `` [18:27:29 ERROR Fishing Info Overlays] This mod failed in the Display.Rendered event. Technical details: FormatException: Input string was not in a correct format. at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) at System.Int32.Parse(String s) at StardewMods.Overlay.Rendered(Object sender, RenderedEventArgs e) in C:\Users\xyr\OneDrive\game\Stardew Valley\FishingInfoOverlays\Overlay.cs:line 218 at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101 ``

The error should be that the itemid of DeluxeBait is non-numeric. The updated itemid has both numbers and non-numbers, and the experience is very bad

**Comment by laz-xyr** [comment]
fix DeluxeBait is non-numeric 
[FishingInfoOverlays 1.1.6-unofficial.2-cyxyr.zip](https://github.com/barteke22/StardewMods/files/14798979/FishingInfoOverlays.1.1.6-unofficial.2-cyxyr.zip)

**Comment by barteke22** [comment]
I've ported the mod to 1.6, but won't be making an official release yet.

From a glance at 1.6, it appears the fishing has been fully redone from scratch, so the hardcoded rewards (like Nuts & bosses) might no longer be accurate / mod could lead to save mutations.

I'm also thinking of adding a performance mode that doesn't constantly simulate fishing (will miss out on fish added via weird methods), as 1.6 made it easier to just add fish via CP (so hopefully there'll be less mods hacking them in).

Here's the current 1.6 port (dunno if it works better or worse than @crazy531's): old

**Comment by ER-95** [comment]
@barteke22 When you say it could lead to save mutations, would you be able to elaborate on that please? Do you mean corrupted saves or something else?

**Comment by barteke22** [comment]
Unfortunately the old fishing (which likely hasn't changed much on that part) had a lot of hardcoded stuff all over the place.
Like Nuts / Furniture editing specific fields directly on Game1.player instead of the passed Farmer object.

Most of the hardcoded stuff could've been bypassed by just passing a 'dummy farmer' to the function, but those specific ones had to be undone after each 'cast' instead.  If any of those flags have changed, the real player might no longer be able to catch some item.

All the things I tested so far seemed to work the same, but I'll need to properly examine the code as fishing used to be (and probably still is) all over the place.

**Comment by benny-dreamly** [comment]
Thank you for coming back to this even after 3 years. I really appreciate it.

**Comment by laz-xyr** [comment]
Welcome back. The latest fix code is in  [repo](https://github.com/crazy531/Stardew-Valley-mod/tree/main/FishingInfoOverlays)，Hope it helps you

**Comment by N3rdGirl64** [comment]
I want to say that the mod, for some reason, causes an issue when quitting to desktop from in a save. It causes the game to hang and not close for like 4-5 min XD

**Comment by barteke22** [comment]
I'm not experiencing that on my end, does your log say anything?


This might be a working version (don't have time to run splitscreen / multiplayer / thorough tests).  Make sure to delete old config files.

**Comment by dsf3449** [comment]
I'm experiencing the same thing, where is the log file located? I can upload it

**Comment by KariArisu** [comment]
Using the version you just linked, Zoom Level affects the size of the overlay. UI Scale doesn't affect it though.

Only really noticeable because I use a mod that lets me quickly change zoom level, which causes this mod's overlay to get smaller and bigger.

Also, doesn't seem to work in the mines.

**Comment by barteke22** [comment]
Log instructions + link generator: https://smapi.io/log

**Comment by QcMitsou** [comment]
[Smapi Log](https://smapi.io/log/7f0c7424154042c9948fba99e4762013) Shows errors with this mod and the fish/percentages overlay doesn't show up in the mines fishing levels.
